=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/benchmark.dtd
<!ELEMENT benchmark (measures,startOn,stopOn,function,sceneUpdater)>

<!ELEMENT measures (time*,collision*,positionError*, distance*, euclideanNorm*, objectCenteredOnCam*, reconstruction3D*, pathFollowing*)>

<!-- benchmark -->
<!ELEMENT startOn (type,target?,position?)>
<!ELEMENT stopOn (type,target?,position?)>
<!ELEMENT function (#PCDATA)>
<!ATTLIST function publishResult (true|false) "false">
<!ATTLIST function publishRate CDATA #IMPLIED>

<!-- Measures -->
<!ELEMENT time (name,log?,startOn,stopOn)>
<!ELEMENT collision (name,target,log?,startOn,stopOn)>
<!ELEMENT positionError (name,target,position,topic?,log?,startOn,stopOn)>
<!ELEMENT distance (name,target,log?,startOn,stopOn)>
<!ELEMENT euclideanNorm (name,groundTruth,target,log?,startOn,stopOn)>
<!ELEMENT objectCenteredOnCam (name,target,camera,log?,startOn,stopOn)>
<!ELEMENT reconstruction3D (name,target, topic, from, levelOfDetail?, log?,startOn,stopOn)>
<!ATTLIST reconstruction3D detailedResultsToGlobals (true|false) "false">
<!ELEMENT pathFollowing (name, target, topic?, from?, log?,startOn,stopOn)>

<!-- Trigger -->
<!ELEMENT type (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT position (x,y,z)>


<!-- Position -->
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT log (#PCDATA)>

<!-- Euclidean Norm -->
<!ELEMENT groundTruth ((value+)|(camera,target,publishOn?)|(from,to))>
<!ELEMENT camera (#PCDATA)>
<!ELEMENT publishOn (#PCDATA)>
<!ATTLIST groundTruth type (constant|cornersFromCamera|centroidFromCamera|relativeLocation) #REQUIRED>

<!ELEMENT value (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>

<!-- reconstruction3D -->
<!ELEMENT topic (#PCDATA)>
<!ELEMENT levelOfDetail (#PCDATA)>

<!-- SceneUpdater -->

<!ELEMENT sceneUpdater (none | sceneFogUpdater | currentForceUpdater | armMoveUpdater | repeat | sceneLightUpdater | cameraNoiseUpdater | bagFogUpdater)>

<!ELEMENT none EMPTY>

<!ELEMENT sceneFogUpdater (initialValue, finalValue, step, interval,sceneUpdater?)>
<!ELEMENT bagFogUpdater (initialValue, finalValue, step, interval, bag, imageTopic, infoTopic, imageDepth, imagePub?, infoPub?,  sceneUpdater?)>
<!ELEMENT currentForceUpdater (initialValue, finalValue, sphericalDirection, forceVariation, forcePeriod, directionVariation, directionPeriod, random, step, interval, target,sceneUpdater?)>
<!ATTLIST currentForceUpdater publishAsForce (true|false) "false">
<!ELEMENT armMoveUpdater (armPosition+, step, interval, target,sceneUpdater?)>
<!ELEMENT repeat (iterations, interval,sceneUpdater?)>
<!ELEMENT sceneLightUpdater (initialValue, finalValue, step, interval,sceneUpdater?)>
<!ELEMENT cameraNoiseUpdater (initialValue, finalValue, step, interval,sceneUpdater?)>

<!ELEMENT armPosition (joint+)>
<!ELEMENT joint (#PCDATA)>
<!ELEMENT initialValue (#PCDATA)>
<!ELEMENT finalValue (#PCDATA)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT interval (#PCDATA)>
<!ELEMENT iterations (#PCDATA)>

<!ELEMENT bag (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT imageDepth (#PCDATA)>
<!ELEMENT imagePub (#PCDATA)>
<!ELEMENT infoPub (#PCDATA)>

<!-- Current -->
<!ELEMENT sphericalDirection (theta, phi)>
<!ELEMENT directionVariation (theta, phi)>
<!ELEMENT directionPeriod (theta, phi)>
<!ELEMENT theta (#PCDATA)>
<!ELEMENT phi (#PCDATA)>
<!ELEMENT forceVariation (#PCDATA)>
<!ELEMENT forcePeriod (#PCDATA)>
<!ELEMENT random (#PCDATA)>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/trackingBenchmarkauto.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <euclideanNorm>
      <name>corners</name>
      <groundTruth type="cornersFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
	<publishOn> autoInit</publishOn>
      </groundTruth>	
      <target> cornersTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <euclideanNorm>
      <name>centroid</name>
      <groundTruth type="centroidFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
      </groundTruth>	
      <target> centroidTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <objectCenteredOnCam>
      <name>objectCentered</name>
      <target>blackbox</target>
      <camera>bowtech1</camera>
      <log>0.1</log>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </objectCenteredOnCam>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function>corners+centroid</function>

  <sceneUpdater> 
    <currentForceUpdater>
      <initialValue>0</initialValue>
      <finalValue>0.2</finalValue>
      <sphericalDirection>
	<theta> 1.57 </theta>
	<phi> 0 </phi>
      </sphericalDirection>
      <forceVariation> 0.005 </forceVariation>
      <forcePeriod> 4 </forcePeriod>
      <directionVariation>
	<theta> 0 </theta>
	<phi> 0.7 </phi>	
      </directionVariation>
      <directionPeriod>
	<theta> 4 </theta>
	<phi> 30 </phi>	
      </directionPeriod>
      <random> 0.01 </random>
      <step>0.01</step>
      <interval>120</interval>
      <target>girona500</target>
    </currentForceUpdater>
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/pipeFollowing.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <time>
      <name>taskTime</name>
      <startOn>
        <type>onInit</type>
      </startOn>
      <stopOn>
         <type>never</type>
      </stopOn>
    </time>

    <positionError>	
      <name>positionError</name>
      <target> girona500 </target>
      <position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </position>
      <topic> position </topic>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </positionError>

    <pathFollowing>
      <name>pathFollowing</name>
      <target> girona500 </target>
      <topic> path </topic>
      <from> localizedWorld </from>
      <log> 0.1 </log>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </pathFollowing>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>service</type>
     <target> stopBench </target>
  </stopOn> 
    
  <function publishRate="0.5" publishResult="true">taskTime</function>

  <sceneUpdater> 
    <none />
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/visionBenchmarkRecursive.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <euclideanNorm>
      <name>corners</name>
      <groundTruth type="cornersFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
	<publishOn> autoInit</publishOn>
      </groundTruth>	
      <target> cornersTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <euclideanNorm>
      <name>centroid</name>
      <groundTruth type="centroidFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
      </groundTruth>	
      <target> centroidTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function>corners+centroid</function>


  <sceneUpdater> 
    <currentForceUpdater>
      <initialCurrent>0.05</initialCurrent>
      <finalCurrent>0.05</finalCurrent>
      <sphericalDirection>
      <theta> 1.57 </theta>
        <phi> 0 </phi>
        </sphericalDirection>
      <forceVariation> 0.01 </forceVariation>
      <forcePeriod> 1 </forcePeriod>
      <directionVariation>
	<theta> 0 </theta>
	<phi> 2.43 </phi>	
      </directionVariation>
      <directionPeriod>
  	<theta> 4 </theta>
  	<phi> 4 </phi>	
      </directionPeriod>
      <random> 0.1 </random>
      <step>0.02</step>
      <interval>10</interval>
      <target>girona500</target>
      <sceneUpdater> 
        <sceneFogUpdater>
          <initialFog>0</initialFog>
          <finalFog>2.0</finalFog>
          <step>0.05</step>
          <interval>5</interval>
        </sceneFogUpdater>
      </sceneUpdater>
    </currentForceUpdater>
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/reconstruction.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <reconstruction3D detailedResultsToGlobals="true">
      <name>reconstruction</name>	
      <target> blackbox </target>
      <!--<topic> /stereo_down/points2 </topic>
      <from> real_stereo_down </from>-->
      <topic> /LaserReconstructionPointCloud </topic>
      <from> kinematic_base </from>
      <levelOfDetail>0.01</levelOfDetail>
      <log>0.1</log>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </reconstruction3D>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function publishResult="true">reconstruction</function>

  <sceneUpdater> 
    <sceneLightUpdater>
      <initialValue>0.00</initialValue>
      <finalValue>1.02</finalValue>
      <step>0.05</step>
      <interval>20</interval>
    </sceneLightUpdater>
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/simpleBenchmark.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <time>
      <name>taskTime</name>
      <startOn>
        <type>onMove</type>
        <target> girona500 </target>
      </startOn>
      <stopOn>
         <type>never</type>
      </stopOn>
    </time>

    <distance>
      <name>distance</name>
      <target> girona500 </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </distance>
  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>service</type>
     <target> stopBench </target>
  </stopOn> 
    
  <function>taskTime</function>

  <sceneUpdater> 
    <none />
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/visionBenchmarkauto.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <euclideanNorm>
      <name>corners</name>
      <groundTruth type="cornersFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
	<publishOn> autoInit</publishOn>
      </groundTruth>	
      <target> cornersTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <euclideanNorm>
      <name>centroid</name>
      <groundTruth type="centroidFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
      </groundTruth>	
      <target> centroidTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function publishResult="true">corners+centroid</function>

  <sceneUpdater> 
    <sceneFogUpdater>
      <initialValue>0</initialValue>
      <finalValue>2.0</finalValue>
      <step>0.05</step>
      <interval>5</interval>
    </sceneFogUpdater>
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/visionBenchmark.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <euclideanNorm>
      <name>corners</name>
      <groundTruth type="constant">
	<value>215</value>
	<value>149</value>
	<value>300</value>
	<value>149</value>
	<value>300</value>
	<value>176</value>
	<value>215</value>
	<value>176</value>
      </groundTruth>	
      <target> cornersTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <euclideanNorm>
      <name>centroid</name>
      <groundTruth type="constant">
	<value>257.5 </value>
	<value>162.5</value>
      </groundTruth>	
      <target> centroidTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function>corners+centroid</function>

  <sceneUpdater> 
    <sceneFogUpdater>
      <initialValue>0</initialValue>
      <finalValue>1.3</finalValue>
      <step>0.05</step>
      <interval>2</interval>
    </sceneFogUpdater>
  </sceneUpdater>

</benchmark>

=== paper-use/uwsim_test2/uwsimbenchmarks/uwsimbenchmarks/data/testbenchmark.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <time>
      <name>taskTime</name>
      <startOn>
        <type>onInit</type>
        <target> girona500 </target>
      </startOn>
      <stopOn>
         <type>never</type>
         <target> girona500 </target>
      </stopOn>
    </time>

    <collision>
      <name>Collisions</name>
      <target> girona500 </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </collision>

    <positionError>
      <name>positionError</name>
      <target>blackbox</target>
      <position>
        <x>0</x>
        <y>0</y>
        <z>3.65</z>
      </position>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </positionError>

    <distance>
      <name>distance</name>
      <target> girona500 </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </distance>

    <euclideanNorm>
      <name>euclideanNorm</name>
      <groundTruth type="constant">
	<value>0.2 </value>
	<value> 1.5</value>
	<value> 2.1 </value>
      </groundTruth>	
      <target> testtopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>
  </measures>

  <startOn>
     <type>onInit</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
     <target> asd</target>
  </stopOn> 
    
  <function>taskTime</function>

  <sceneUpdater> 
    <none />
  </sceneUpdater>

</benchmark>
